-- Role
CREATE ROLE django WITH LOGIN PASSWORD 'password';
CREATE ROLE op_write WITH LOGIN PASSWORD 'password_write';
CREATE ROLE op_read WITH LOGIN PASSWORD 'password_read';

-- Database
CREATE DATABASE cobweb;
\c cobweb;
CREATE SCHEMA AUTHORIZATION django;
GRANT CONNECT ON DATABASE cobweb TO django;
GRANT CONNECT ON DATABASE cobweb TO op_write;
GRANT CONNECT ON DATABASE cobweb TO op_read;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA django TO django;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA django TO op_write;
GRANT SELECT ON ALL TABLES IN SCHEMA django TO op_read;
