services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    container_name: cobwebserver
    ports:
      - "8000:8000"
    volumes:
      - .:/code
