services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    # For Debug
    # command: python3 manage.py runserver 0.0.0.0:8000
    command: uwsgi --http :8000 --wsgi-file cobweb/wsgi.py
    container_name: cobwebserver
    ports:
      - "8000:8000"
