services:
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: cobwebdb
    ports:
      - 5432:5432
    volumes:
      - ./init/${PROFILE}:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
