name: Hadolint Server
on:
  pull_request:
    types: [synchronize, opened, reopened]
  push:
    branches:
      - main
jobs:
  hadolint-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: server/Dockerfile
