name: Test App
on:
  pull_request:
    types: [synchronize, opened, reopened]
  push:
    branches:
      - main
jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Test
        run: pnpm run test
      - name: Lint
        run: pnpm run lint
